name: moonlander
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  drift: ^1.1.0
  flame: ^1.0.0
  flame_audio: ^1.0.0
  path: ^1.8.0
  path_provider: ^2.0.0
  sqlite3_flutter_libs: ^0.5.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^1.1.0
  build_runner: ^2.1.5
  very_good_analysis: ^2.4.0
  

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/
     - assets/audio/
  fonts:
     - family: AldotheApache
       fonts:
         - asset: assets/font/AldotheApache.ttf